# 020_Cadastro_de_usuario

- Att
    - resources/usuario.py          >> (1,2,3,4,5,6)
    - app.py                        >> (7)
    - models/usuario.py             >> (8)

- Observação
    - Algumas correções em resourses/usuario.py foram efetuadas pois erros estavam ocasionando o não funcionamento dos metodos get e delete do resourses/usuario.py, a mensagem de erro também estava incorreta e foi corrigida 